import standardConfig from 'eslint-config-standard'
import jsxConfig from 'eslint-config-standard-jsx'
import typescriptConfig from 'eslint-config-standard-with-typescript'
import flowPlugin from 'eslint-plugin-flow'

import packageJson from '../../package.json'
import { removeProps, splitArray, splitObject } from '../utils.js'
import { filterStyleRules } from './style-rules.js'

/**
 * Generate a single eslint config file.
 */
function makeFile(info) {
  const { comment, upstream, config } = info
  return (
    `// ${comment}\n` +
    '//\n' +
    `// Auto-generated by ${packageJson.name}\n` +
    `// based on rules from ${upstream}\n` +
    '\n' +
    '"use strict";\n' +
    '\n' +
    `module.exports = ${JSON.stringify(config, null, 2)};\n`
  )
}

/**
 * Generates a pair of eslint config files (with and without style rules).
 */
async function makeFilePair(out, name, info) {
  const { comment, upstream, config } = info

  // Make normal version:
  out[`${name}.js`] = makeFile({
    comment: `${comment} for Standard.js`,
    upstream,
    config
  })

  // Make `lint` version:
  out[`lint/${name}.js`] = makeFile({
    comment: `${comment} for Standard.js (without style rules)`,
    upstream,
    config: filterStyleRules(config)
  })
}

/**
 * Generates all the eslint config files in this package.
 */
function makeFiles() {
  const out = {}
  const isNode = rule => /^node/.test(rule)
  const splitNodeEnv = splitObject(standardConfig.env, isNode)
  const splitNodePlugins = splitArray(standardConfig.plugins, isNode)
  const splitNodeRules = splitObject(standardConfig.rules, isNode)

  makeFilePair(out, 'index', {
    comment: 'Core rules',
    upstream: 'eslint-config-standard',
    config: {
      ...standardConfig,
      env: splitNodeEnv.no,
      globals: {
        clearInterval: 'readonly',
        clearTimeout: 'readonly',
        console: 'readonly',
        setInterval: 'readonly',
        setTimeout: 'readonly',
        ...standardConfig.globals
      },
      plugins: splitNodePlugins.no,
      rules: splitNodeRules.no
    }
  })

  makeFilePair(out, 'node', {
    comment: 'Node.js support',
    upstream: 'eslint-config-standard',
    config: {
      env: splitNodeEnv.yes,
      plugins: splitNodePlugins.yes,
      rules: splitNodeRules.yes
    }
  })

  makeFilePair(out, 'jsx', {
    comment: 'JSX support',
    upstream: 'eslint-config-standard-jsx',
    config: jsxConfig
  })

  makeFilePair(out, 'flow', {
    comment: 'Flow language support',
    upstream: 'eslint-plugin-flow',
    config: {
      plugins: ['flowtype'],
      ...flowPlugin.configs.recommended
    }
  })

  makeFilePair(out, 'typescript', {
    comment: 'Typescript language support',
    upstream: 'eslint-config-standard-with-typescript',
    config: {
      ...removeProps(typescriptConfig, ['extends', 'parser']),
      overrides: [
        {
          parser: '@typescript-eslint/parser',
          ...typescriptConfig.overrides[0]
        }
      ]
    }
  })

  return out
}

export const ruleFiles = makeFiles()
