const { makeNodeDisklet } = require('disklet')
const { join } = require('path')
const packageJson = require('../package.json')

const { filterStyleRules } = require('./style-rules.js')

const disklet = makeNodeDisklet(join(__dirname, '..'))

/**
 * Write out a single config file.
 */
function writeConfig(info) {
  const { filename, comment, upstream, config } = info

  const body = `// ${comment}
//
// Auto-generated by ${packageJson.name}
// based on rules from ${upstream}

"use strict";

module.exports = ${JSON.stringify(config, null, 2)};
`

  return disklet.setText(filename, body)
}

/**
 * Write out a set of config files (with and without style rules).
 */
function writeConfigs(info) {
  const { name, comment, upstream, config } = info

  // Write normal version:
  writeConfig({
    filename: `${name}.js`,
    comment: `${comment} for Standard.js`,
    upstream,
    config
  })

  // Write `lint` version:
  writeConfig({
    filename: `lint/${name}.js`,
    comment: `${comment} for Standard.js (without style rules)`,
    upstream,
    config: filterStyleRules(config)
  })
}

module.exports = { writeConfigs }
