const { makeNodeDisklet } = require('disklet')
const { join } = require('path')
const packageJson = require('../package.json')

const { filterStyleRules } = require('./style-rules.js')

const disklet = makeNodeDisklet(join(__dirname, '..'))

function stringifyConfig(comment, config) {
  return `// ${comment}
// Auto-generated by ${packageJson.name}
"use strict";

module.exports = ${JSON.stringify(config, null, 2)};
`
}

/**
 * Writes out two copies of a config, one with format rules and one without.
 */
function writeConfig(name, comment, config) {
  const lintConfig = filterStyleRules(config)

  disklet.setText(`${name}.js`, stringifyConfig(`${comment} rules`, config))
  disklet.setText(
    `lint/${name}.js`,
    stringifyConfig(`${comment} rules without formatting`, lintConfig)
  )
}

function writeConfigs(configs) {
  for (const name in configs) {
    const { comment, config } = configs[name]
    writeConfig(name, comment, config)
  }
}

module.exports = { writeConfigs }
